sudo: required
dist: trusty
group: deprecated-2017Q4

language: go

services:
  - docker

addons:
  postgresql: "9.6"

go:
  - "1.16"

before_install:
  - ./script/check_formatting.sh
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx

install:
  - make setup
  - docker buildx create --use

script:
  - make build
  - make test
  - make test-all
  - make docker-release